apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      initContainers:
        - name: install-code
          image: app-placeholder
          # Copia o novo conte√∫do da imagem (/var/www/html) para o volume (/target)
          # Copia tudo da imagem para o volume vazio, garantindo que o Nginx veja os assets
          # Usamos o comando 'rsync' ou um 'cp' mais simples sem preservar atributos
          command: ["sh", "-c", "rm -rf /target/* && cp -R /var/www/html/* /target/"]
          volumeMounts:
            - name: app-code
              mountPath: /target
          securityContext:
            runAsUser: 0 # Roda como root para ter poder de limpeza no volume
      containers:
        # --- CONTAINER 1: PHP-FPM ---
        - name: php-fpm
          image: app-placeholder
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html  
          readinessProbe:
            exec:
              command: ["php-fpm-healthcheck"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["php-fpm-healthcheck"]
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: app-secrets

        # --- CONTAINER 2: NGINX (Sidecar) ---
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:
        - name: app-code
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80