apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      initContainers:
        - name: install-code
          image: app-placeholder
          # 1. Limpa o volume
          # 2. Copia os arquivos da imagem para o volume
          # 3. Dá a posse das pastas para o usuário 33 (www-data)
          command: 
            - "sh"
            - "-c"
            - |
              rm -rf /target/* && \
              cp -rf /var/www/html/. /target/ && \
              chown -R 33:33 /target/storage /target/bootstrap/cache && \
              chmod -R 775 /target/storage /target/bootstrap/cache
          volumeMounts:
            - name: app-code
              mountPath: /target
          securityContext:
            runAsUser: 0 # Roda como root para ter poder de limpeza no volume
      containers:
        # --- CONTAINER 1: PHP-FPM ---
        - name: php-fpm
          image: app-placeholder
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html  
          readinessProbe:
            exec:
              command: ["php-fpm-healthcheck"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["php-fpm-healthcheck"]
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: app-secrets

        # --- CONTAINER 2: NGINX ---
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

        # --- CONTAINER 3: PULSE ---
        - name: pulse-worker
          image: app-placeholder
          command: ["php", "artisan", "pulse:check"]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
          envFrom:
            - secretRef:
                name: app-secrets
      volumes:
        - name: app-code
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80