apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: homolog
  annotations:
    # Esta annotation é o que o seu Controller (versão 7cfc98...) procura
    kubernetes.io/ingress.class: "nginx"
    # Força o redirecionamento para HTTPS se você tiver SSL,
    # mas por enquanto vamos garantir que o HTTP funcione
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # Reduzi para 3 requisições por segundo.
    # Isso vai dar erro nos bots.
    # nginx.ingress.kubernetes.io/limit-rps: "3"
    # nginx.ingress.kubernetes.io/limit-burst-multiplier: "2"
spec:
  # O preenchimento deste campo fará o CLASS sair de <none> para nginx
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80
