name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

jobs:
  ci-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Setup do Ambiente PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql, bcmath, sqlite3
      
      - name: Install dependencies
        run: composer install --ignore-platform-reqs

      # 2. Preparação e Qualidade
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          
      - name: Check Code Style
        run: ./vendor/bin/pint --test

      # 3. Testes de Integração e Unitários
      - name: Run Unit and Feature Tests
        run: php artisan test --env=testing
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

      # 4. Docker Build & Push
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/php/Dockerfile
          target: prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/app-laravel:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/app-laravel:${{ github.sha }}
      
      # 5. Preparação dos Manifestos
      - name: Update Kubernetes resources
        run: |
          cd k8s/homolog
          kustomize edit set image app-placeholder=${{ secrets.DOCKERHUB_USERNAME }}/app-laravel:${{ github.sha }}

          sed -i "s/PLACEHOLDER_DB_HOST/${{ secrets.DB_HOST }}/g" kustomization.yaml
          sed -i "s/PLACEHOLDER_DB_PORT/${{ secrets.DB_PORT }}/g" kustomization.yaml
          sed -i "s/PLACEHOLDER_DB_DATABASE/${{ secrets.DB_DATABASE }}/g" kustomization.yaml
          sed -i "s/PLACEHOLDER_DB_USERNAME/${{ secrets.DB_USERNAME }}/g" kustomization.yaml
          sed -i "s/PLACEHOLDER_DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g" kustomization.yaml
          sed -i "s/PLACEHOLDER_APP_KEY/${{ secrets.APP_KEY }}/g" kustomization.yaml

      # 6. Autenticação na DigitalOcean
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

      # 7. Deploy Real (A Mágica!)
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8s/homolog --load-restrictor LoadRestrictionsNone